import { Injectable } from '@angular/core';
import { word } from '../models/word.interface';
@Injectable({
  providedIn: 'root',
})
export class WordsService {
  constructor() {}
  private words: word[] = [
    { word: 'love', translation: 'אהבה', used: false },
    { word: 'heart', translation: 'לב', used: false },
    { word: 'dream', translation: 'חלום', used: false },
    { word: 'night', translation: 'לילה', used: false },
    { word: 'song', translation: 'שיר', used: false },
    { word: 'music', translation: 'מוזיקה', used: false },
    { word: 'dance', translation: 'ריקוד', used: false },
    { word: 'moonlight', translation: 'אור ירח', used: false },
    { word: 'melody', translation: 'מנגינה', used: false },
    { word: 'memory', translation: 'זיכרון', used: false },
    { word: 'rain', translation: 'גשם', used: false },
    { word: 'tears', translation: 'דמעות', used: false },
    { word: 'smile', translation: 'חיוך', used: false },
    { word: 'kiss', translation: 'נשיקה', used: false },
    { word: 'fire', translation: 'אש', used: false },
    { word: 'wind', translation: 'רוח', used: false },
    { word: 'star', translation: 'כוכב', used: false },
    { word: 'light', translation: 'אור', used: false },
    { word: 'darkness', translation: 'חושך', used: false },
    { word: 'shadow', translation: 'צל', used: false },
    { word: 'soul', translation: 'נשמה', used: false },
    { word: 'heaven', translation: 'שמיים', used: false },
    { word: 'angel', translation: 'מלאך', used: false },
    { word: 'devil', translation: 'שטן', used: false },
    { word: 'whisper', translation: 'לחישה', used: false },
    { word: 'shout', translation: 'צעקה', used: false },
    { word: 'lonely', translation: 'בודד', used: false },
    { word: 'forever', translation: 'לנצח', used: false },
    { word: 'pain', translation: 'כאב', used: false },
    { word: 'hope', translation: 'תקווה', used: false },
    { word: 'fear', translation: 'פחד', used: false },
    { word: 'wings', translation: 'כנפיים', used: false },
    { word: 'flight', translation: 'טיסה', used: false },
    { word: 'goodbye', translation: 'להתראות', used: false },
    { word: 'awakening', translation: 'התעוררות', used: false },
    { word: 'hello', translation: 'שלום', used: false },
    { word: 'freedom', translation: 'חירות', used: false },
    { word: 'mystery', translation: 'תעלומה', used: false },
    { word: 'truth', translation: 'אמת', used: false },
    { word: 'lie', translation: 'שקר', used: false },
    { word: 'road', translation: 'דרך', used: false },
    { word: 'river', translation: 'נהר', used: false },
    { word: 'mountain', translation: 'הר', used: false },
    { word: 'ocean', translation: 'אוקיינוס', used: false },
    { word: 'storm', translation: 'סערה', used: false },
    { word: 'silence', translation: 'שקט', used: false },
    { word: 'friend', translation: 'חבר', used: false },
    { word: 'enemy', translation: 'אויב', used: false },
    { word: 'war', translation: 'מלחמה', used: false },
    { word: 'peace', translation: 'שלום', used: false },
    { word: 'destiny', translation: 'גורל', used: false },
    { word: 'fate', translation: 'גורל', used: false },
    { word: 'faith', translation: 'אמונה', used: false },
    { word: 'grace', translation: 'חן', used: false },
    { word: 'cry', translation: 'לבכות', used: false },
    { word: 'happiness', translation: 'אושר', used: false },
    { word: 'loneliness', translation: 'בדידות', used: false },
    { word: 'passion', translation: 'תשוקה', used: false },
    { word: 'embrace', translation: 'חיבוק', used: false },
    { word: 'scream', translation: 'צרחה', used: false },
    { word: 'cold', translation: 'קר', used: false },
    { word: 'warm', translation: 'חם', used: false },
    { word: 'burn', translation: 'לשרוף', used: false },
    { word: 'broken', translation: 'שבור', used: false },
    { word: 'fix', translation: 'לתקן', used: false },
    { word: 'wander', translation: 'לנדוד', used: false },
    { word: 'home', translation: 'בית', used: false },
    { word: 'jewel', translation: 'תכשיט', used: false },
    { word: 'longing', translation: 'געגוע', used: false },
    { word: 'mirror', translation: 'מראה', used: false },
    { word: 'reflection', translation: 'השתקפות', used: false },
    { word: 'rainbow', translation: 'קשת', used: false },
    { word: 'butterfly', translation: 'פרפר', used: false },
    { word: 'sunshine', translation: 'אור שמש', used: false },
    { word: 'castle', translation: 'טירה', used: false },
    { word: 'crown', translation: 'כתר', used: false },
    { word: 'silver', translation: 'כסף', used: false },
    { word: 'heartbeat', translation: 'פעימות לב', used: false },
    { word: 'thunder', translation: 'רעם', used: false },
    { word: 'diamond', translation: 'יהלום', used: false },
    { word: 'universe', translation: 'יקום', used: false },
    { word: 'paradise', translation: 'גן עדן', used: false },
    { word: 'rose', translation: 'ורד', used: false },
    { word: 'perfume', translation: 'בושם', used: false },
    { word: 'symphony', translation: 'סימפוניה', used: false },
    { word: 'magic', translation: 'קסם', used: false },
    { word: 'spell', translation: 'כישוף', used: false },
    { word: 'enchantment', translation: 'כישוף', used: false },
    { word: 'lightning', translation: 'ברק', used: false },
    { word: 'fragile', translation: 'שביר', used: false },
    { word: 'echo', translation: 'הד', used: false },
    { word: 'horizon', translation: 'אופק', used: false },
    { word: 'breeze', translation: 'בריזה', used: false },
    { word: 'illusion', translation: 'אשליה', used: false },
    { word: 'midnight', translation: 'חצות', used: false },
    { word: 'desire', translation: 'תשוקה', used: false },
    { word: 'glory', translation: 'תהילה', used: false },
    { word: 'curse', translation: 'קללה', used: false },
    { word: 'butterflie', translation: 'פרפר', used: false },
    { word: 'serenade', translation: 'סרנדה', used: false },
    { word: 'lullaby', translation: 'שיר ערש', used: false },
    { word: 'starlight', translation: 'אור כוכבים', used: false },
    { word: 'invisible', translation: 'בלתי נראה', used: false },
    { word: 'eternity', translation: 'נצח', used: false },
    { word: 'promise', translation: 'הבטחה', used: false },
    { word: 'miracle', translation: 'נס', used: false },
    { word: 'destined', translation: 'נועד', used: false },
    { word: 'romance', translation: 'רומנטיקה', used: false },
    { word: 'surrender', translation: 'כניעה', used: false },
    { word: 'wild', translation: 'פראי', used: false },
    { word: 'gentle', translation: 'עדין', used: false },
    { word: 'soft', translation: 'רך', used: false },
    { word: 'inspire', translation: 'לעורר השראה', used: false },
    { word: 'escape', translation: 'בריחה', used: false },
    { word: 'wanderlust', translation: 'כמיהה לנדודים', used: false },
    { word: 'unbreakable', translation: 'בלתי שביר', used: false },
    { word: 'gold', translation: 'זהב', used: false },
    { word: 'feather', translation: 'נוצה', used: false },
    { word: 'sunset', translation: 'שקיעה', used: false },
    { word: 'dawn', translation: 'שחר', used: false },
    { word: 'fireworks', translation: 'זיקוקים', used: false },
    { word: 'temptation', translation: 'פיתוי', used: false },
    { word: 'hug', translation: 'חיבוק', used: false },
    { word: 'shiver', translation: 'רעד', used: false },
    { word: 'journey', translation: 'מסע', used: false },
    { word: 'path', translation: 'שביל', used: false },
    { word: 'wanderer', translation: 'נודד', used: false },
    { word: 'nomad', translation: 'נווד', used: false },
    { word: 'traveler', translation: 'מטייל', used: false },
    { word: 'adventure', translation: 'הרפתקה', used: false },
    { word: 'mystical', translation: 'מיסטי', used: false },
    { word: 'enigma', translation: 'חידה', used: false },
    { word: 'oracle', translation: 'אורקל', used: false },
    { word: 'prophecy', translation: 'נבואה', used: false },
    { word: 'secret', translation: 'סוד', used: false },
    { word: 'hidden', translation: 'מוסתר', used: false },
    { word: 'veil', translation: 'רעלה', used: false },
    { word: 'guardian', translation: 'שומר', used: false },
    { word: 'knight', translation: 'אביר', used: false },
    { word: 'shield', translation: 'מגן', used: false },
    { word: 'sword', translation: 'חרב', used: false },
  ];

  public getWord(): word {
    let marked: boolean = true;
    let counter: number = 0;
    while (marked) {
      const index = Math.floor(Math.random() * this.words.length);
      if (this.words[index].used === false) {
        this.words[index].used = true;
        marked = false;
        const result = this.words[index];
        console.log(`Random word = ${result.word}`);
        console.log(this.words);

        return result;
      }
      counter++;
      if (counter == this.words.length) {
        break;
      }
    }
    console.log(`all Words used..`);
    return { word: 'null', translation: 'null', used: false };
  }
}
